### PR TITLE
Respect special_tokens_map.json.

### PR DESCRIPTION
**Pull request by yk-goblin**
Some models have special token mapping by `special_tokens_map.json` such as [this](https://huggingface.co/colorfulscoop/sbert-base-ja/blob/main/special_tokens_map.json)

This PR add support the mapping.

### CODE REVIEW

**Comment by guillaume-be** [comment]
Hello @yk-goblin ,

Thank you for raising this and for the pull request. I had a quick look and generally it looks good. A few questions on my side:
- I believe the `special_tokens_map.json` is not specific to DeBERTa -- would it make sense to update the mechanism so that all models could take this special map as an input?
- The current implementation introduces breaking changes (possibly for all tokenizers) for a special token map that is seldom used -- would it make sense to create a public `new_with_special_token_map` method, and keep the `new` method? The `new` method could just call `new_with_special_token_map` with the `Default` token mapping, but this has the benefit of preserving backward compatibility
- The `unknown_value`  for `Vocab` change may be problematic for downstream crates relying on this common special token - is there a way to keep backward compatibility for this field as well?

**Comment by yk-goblin** [comment]
@guillaume-be Hi, thank you for checking this PR.

> believe the special_tokens_map.json is not specific to DeBERTa -- would it make sense to update the mechanism so that all models could take this special map as an input?

Ultimately I think that's preferable.

> The current implementation introduces breaking changes (possibly for all tokenizers) for a special token map that is seldom used -- would it make sense to create a public new_with_special_token_map method, and keep the new method? The new method could just call new_with_special_token_map with the Default token mapping, but this has the benefit of preserving backward compatibility

Is the `new` method you are talking about the current `from_file` method?
Our goal is to use this added functionality from rust-bert, so we changed the `from_file`, but it would be nice to add the `new_with_special_token_map` method to minimize breaking changes.

> The unknown_value for Vocab change may be problematic for downstream crates relying on this common special token - is there a way to keep backward compatibility for this field as well?

Unfortunately this would require a breaking change to the Voca trait.

Thank you.

**Comment by guillaume-be** [comment]
@yk-goblin would you be willing to extend the support of `special_token_map_config.json` to other tokenizers or would you need support to do so?

**Comment by guillaume-be** [comment]
@yk-goblin I have created a PR based on your suggestion that generalizes across the entire library: https://github.com/guillaume-be/rust-tokenizers/pull/78

For compatibility for all tokenizers I had to change the design, but the capabilities should remain the same. I still need to add constructors for the tokenizers to allow creation with custom special token map, but it would be great if you could have a look and review.

**Comment by guillaume-be** [comment]
Thank you again @yk-goblin , closing this as it was Implemented as part of https://github.com/guillaume-be/rust-tokenizers/pull/78

**Pull request closed without merging**
